### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by vladyslav-maryniak** [vladyslav-maryniak/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by marik256** [comment]
– I'm Jonathan Price, simply known as John Price. Captain in the 22nd SAS and commander of Task Force 141. I have many operations under my belt, from the liquidation of Imran Zakhaev in Pripyat, Ukraine, to the destruction of General Roman Barkov's gas factory in Georgia. I specialize in unconventional warfare and has a deep but often strained relationship with the system. Me and my crew get dirty while the world stays clean.

**Comment by vladyslav-maryniak** [comment]
Pretty informative description.
