### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by vladyslav-maryniak** [vladyslav-maryniak/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by marik256** [comment]
_**Life & Education**_

I began my service in the British Army Infantry at the age of sixteen. I completed Special Service Commando selection and was 'badged' a member of the SAS, becoming one of the youngest cadets to ever graduate the Royal Military Academy as a commissioned officer.

_**Languages**_

:uk: English

_**Skills**_

Survival in any situation, invulnerability to damage, lucky, team management, orienteering, motivation, handle a weapon, hand-to-hand combat

_**Character**_

I live by a strict warrior ethos bound by virtues like honor, courage, commitment, loyalty, and integrity. These fundamentals become part of my DNA.

_**Likes**_

Cigars, boonie hats, bad company, my mustache and beard.

_**Dislikes**_

I hate being tied down by rules or procedures.

_**Life Lesson**_

History is written by the victor. History is filled with liars. If he lives, and we die, his truth becomes written - and ours is lost.

**Comment by vladyslav-maryniak** [comment]
Not bad.

**Comment by marik256** [comment]
#### Life & Education
```html
<section>
  <h3>Life & Education</h3>
  <p>I began my service in the British Army Infantry at the age of sixteen. I completed
    Special Service Commando selection and was 'badged' a member of the SAS, becoming one of the youngest
    cadets to ever graduate the Royal Military Academy as a commissioned officer.</p>
</section>
```
#### Languages
```html
<section>
  <h3>Languages</h3>
  <p class="tags small">
    <span class="language" lang="en">
      &#x1F1EC;&#x1F1E7; ENGLISH
    </span>
  </p>
</section>
```
#### Skills
```html
<section>
  <h3>Skills</h3>
  <p class="tags small">SURVIVAL IN ANY SITUATION, INVULNERABILITY TO DAMAGE, LUCKY, TEAM MANAGEMENT,
    ORIENTEERING, MOTIVATION, HANDLE A WEAPON, HAND-TO-HAND COMBAT</p>
</section>
```
#### Character
```html
<section>
  <h3>Character</h3>
  <p>
    I live by a strict warrior ethos bound by virtues like honor, courage, commitment, loyalty, and
    integrity. These fundamentals become part of my DNA.
  </p>
</section>
```
#### Likes
```html
<section>
  <h3>Likes</h3>
  <p>
    I live by a strict warrior ethos bound by virtues like honor, courage, commitment, loyalty, and
    integrity. These fundamentals become part of my DNA.
  </p>
</section>
```
#### Dislikes
```html
<section>
  <h3>Dislikes</h3>
  <p>
    I hate being tied down by rules or procedures.
  </p>
</section>
```
#### Life Lesson
```html
<section>
  <h3>Life Lesson</h3>
  <p>History is written by the victor. History is filled with liars. If he lives, and we die, his truth
    becomes written - and ours is lost.</p>
</section>
```
